# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Multiple config files with CI/CD
defaults:
  run:
    shell: bash

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Step 1 - Echo working directory
        run: |
          pwd
      - name: Step 2 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.DEMO_PROPERTIES_VALUE }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{ secrets.DEMO_PROPERTIES_VALUE }} | sed 's/./& /g'
          echo pwd
      - name: Step 3 - Write secret in app
        run: |
          printf ${{ secrets.DEMO_PROPERTIES_VALUE }} | sed 's/./& /g' >> src/main/resources/applicationconfigb.properties

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify



